# Numpy

NumPy is a library for performing high-performance mathematical computations in Python.

## Main Features:
- Handling of multidimensional arrays (ndarray)
- Efficient mathematical and statistical operations
- Functions for linear algebra and random number generation.

## Installation:
```bash
pip install numpy
```

In [13]:
import numpy as np

## Differences Between Lists and Arrays
- **Lists**: Native Python structure, flexible but less efficient for numerical calculations.
- **Arrays (ndarray)**: NumPy structure, efficient for vectorized operations.

In [14]:
# Ejemplo de suma elemento por elemento
example_list = [1, 2, 3]
example_array = np.array([1, 2, 3])

# For lists: requires manual comprehension
print([x*2 for x in example_list])

# For arrays: vectorized operation
print(example_array * 2)

[2, 4, 6]
[2 4 6]


## Creating Arrays
- **np.array()**: Converts lists or tuples into an ndarray.
- **np.zeros() / np.ones()**: Arrays initialized with 0 or 1.
- **np.arange()**: Numeric sequences with a defined step.
- **np.linspace()**: Numeric sequences with a fixed number of elements.

In [15]:
print(np.array([1, 2, 3]))

[1 2 3]


In [16]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [17]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
print(np.arange(5))

[0 1 2 3 4]


In [19]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


## Important Properties
- **shape**: Array dimensions.
- **dtype**: Data type.
- **size**: Total number of elements.
- **T**: Transpose.

In [20]:
example_matrix = np.array([[1,2,3],[4,5,6]])
example_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
print(example_matrix.shape)

(2, 3)


In [22]:
print(example_matrix.dtype)

int64


In [23]:
print(example_matrix.size)

6


In [24]:
print(example_matrix.T)

[[1 4]
 [2 5]
 [3 6]]


## Basic Operations

```python
# Addition, subtraction, multiplication, division
```

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [26]:
print(a + b)

[5 7 9]


In [27]:
print(a - b)

[-3 -3 -3]


In [28]:
print(a * b)

[ 4 10 18]


In [29]:
print(a / b)

[0.25 0.4  0.5 ]


## Common Errors
```python
 # Error: incompatible dimensions
```

In [30]:
a = np.array([1, 2, 3])
b = np.array([[1], [2]])
# This will raise a ValueError if you try a + b without compatible broadcasting