# Numpy

NumPy es una librería para realizar cálculos matemáticos de alto rendimiento en Python.

## Características principales:
- Manejo de arreglos multidimensionales (ndarray).
- Operaciones matemáticas y estadísticas eficientes.
- Funciones para álgebra lineal y generación de números aleatorios.

## Instalación:
```bash
pip install numpy
```

In [2]:
import numpy as np

## Diferencias entre listas y arreglos
- **Listas**: Estructura nativa de Python, flexible pero menos eficiente en cálculos numéricos.
- **Arreglos (ndarray)**: Estructura de NumPy, eficiente para operaciones vectorizadas.

In [3]:
# Ejemplo de suma elemento por elemento
lista = [1, 2, 3]
arreglo = np.array([1, 2, 3])

# Para listas: se requiere comprensión manual
print([x*2 for x in lista])

# Para arreglos: operación vectorizada
print(arreglo * 2)

[2, 4, 6]
[2 4 6]


## Creación de arreglos
- **np.array()**: Convierte listas o tuplas en un ndarray.
- **np.zeros() / np.ones()**: Arreglos inicializados en 0 o 1.
- **np.arange()**: Secuencias numéricas con paso definido.
- **np.linspace()**: Secuencias numéricas con número fijo de elementos.

In [11]:
print(np.array([1, 2, 3]))

[1 2 3]


In [ ]:
print(np.zeros((2,2)))

In [ ]:
print(np.ones((3, 3)))

In [ ]:
print(np.arange(5))

In [ ]:
print(np.linspace(0, 10, 5))

## Propiedades importantes
- **shape**: Dimensiones del arreglo.
- **dtype**: Tipo de datos.
- **size**: Número total de elementos.
- **T**: Transpuesta.

In [12]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(matriz.shape) # Dimensiones

In [ ]:
print(matriz.dtype) # Tipo de datos

In [ ]:
print(matriz.size) # Número de elementos

In [ ]:
print(matriz.T) # Transpuesta

## Operaciones básicas

```python
# Suma, resta, multiplicación, división
```

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
print(a + b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
print(a - b)

In [ ]:
print(a * b)

In [ ]:
print(a / b)

## Errores comunes
```python
 # Error: dimensiones incompatibles
```

In [8]:
a = np.array([1, 2, 3])
b = np.array([[1], [2]])
# Esto causará ValueError si intentas a + b sin broadcasting compatible